apiVersion: apps/v1
kind: Deployment
metadata:
    name: app-deploy
    labels:
      app: app
spec:
    replicas: 3
    selector:
        matchLabels:
            app: app
    template:
        metadata:
            labels:
                app: app
        spec:
            containers:
                - name: app
                  image: dvdjaco/hello_world:{{ .Values.env.APP_VERSION }}
                  ports:
                    - containerPort: 5000
                  env:
                  - name: NAME
                    value: 'KubeOps :: Hello, world!'
                  - name: IMAGE_TAG
                    value: "{{ .Values.env.APP_VERSION }}"
                  readinessProbe:
                    httpGet:
                        path: /health
                        port: 5000
                    initialDelaySeconds: 10
                    periodSeconds: 10
                    successThreshold: 1
                    failureThreshold: 3
                  livenessProbe:
                    httpGet:
                        path: /health
                        port: 5000
                    initialDelaySeconds: 10
                    periodSeconds: 10
                    timeoutSeconds: 5
                    successThreshold: 1
                    failureThreshold: 3
