name: CD

on:
  push:
    paths:
      - 'version'

env:
  DOCKERHUB_USERNAME: ${{ secrets.DOCKER_USERNAME }}
  DOCKERHUB_KEY: ${{ secrets.DOCKER_KEY }}
  IMAGE_NAME: hello_world

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ env.DOCKERHUB_USERNAME }}
          password: ${{ env.DOCKERHUB_KEY }}

      - name: Read version
        run: VERSION=$(cat version)

      - name: Build Docker image
        run: |
          VERSION=$(cat version)
          docker build -t ${{ env.DOCKERHUB_USERNAME }}/${{ env.IMAGE_NAME }}:$VERSION .

      - name: Push Docker image
        run: |
          VERSION=$(cat version)
          docker push ${{ env.DOCKERHUB_USERNAME }}/${{ env.IMAGE_NAME }}:$VERSION

      - name: Update values.yaml
        run: |
          VERSION=$(cat version)
          cd helm
          sed -i 's|APP_VERSION:.*|APP_VERSION: '$VERSION'|' values.yaml 
          git config --global user.name 'GitHub Actions'
          git config --global user.email 'actions@github.com'
          git add values.yaml
          git commit -m "Update values.yaml"
          git push

